workflows:
  build-ios:
    name: Build iOS
    environment:
      node: latest
    scripts:
      - name: Unzip src folder
        script: |
          unzip -o src.zip -d ./
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      # 注意：这里不要写 "Log in to Expo" 这步
      # 因为 EAS 会自动读取你在网页上设置好的 EXPO_TOKEN
      - name: Build with EAS
        script: |
          eas build --platform ios --profile development --non-interactive
    artifacts:
      - build/ios/ipa/*.ipa
